import streamlit as st
st.title("Alejandra de la Torre")
st.subheader(
    "**Estudiante de Administración y Finanzas** en la Universidad Panamericana")
st.divider ()
st.write("#**EXPERIENCIA**")
st.markdown("**- Tesorera en HP** 2024 - a la fecha")
st.markdown("**- Tesorera en el Comité de Alumnos de la licenciatura en Administración y Finanzas** 2022 - a la fecha")
st.markdown("**- Directora de Sección Femenina Guadalajara Sur Juventud y Familia Misionera** 2022 - a la fecha")
st.markdown("**- Becaria Coordinación de Licenciatura de Administración y Finanzas Universidad Panamericana** 2021 - 2023")
st.divider ()
st.write("#**EDUCACIÓN**")
st.markdown("**- Licenciatura en Administración y Finanzas Universidad Panamericana, campus Guadalajara** 2020 - a la fecha")
st.markdown("**- Especialidad en Finanzas Corporativas** 2023")
st.divider ()
st.write("#**IDIOMAS**")
st.markdown("- Inglés Avanzado")
st.markdown("- Francés Básico")
st.divider ()
st.write("#**HABILIDADES**")
st.markdown("- Certificación de Microsoft Office")
st.markdown("- TOEFL 610 puntos")
st.write("**APTITUDES**")
