import streamlit as st
st.title("Alejandra de la Torre")
st.subheader(
    "**Estudiante de Administración y Finanzas** en la Universidad Panamericana")
st.divider ()
st.write("**DATOS PERSONALES**")
st.markdown("**número:** 33 1417 2999")
st.markdown("**email:** alemariade14@gmail.com")
st.divider ()
st.write("**EXPERIENCIA**")
st.markdown("**_ Tesorera en HP**")
st.write("Fechas: 2024 - a la fecha")
st.markdown("**- Tesorera en el Comité de Alumnos de la licenciatura en Administración y Finanzas**")
st.write("Fechas: 2022 - a la fecha")
st.markdown("**- Directora de Sección Femenina Guadalajara Sur Juventud y Familia Misionera**")
st.write("Fechas: 2022 - a la fecha")
st.markdown("**- Becaria Coordinación de Licenciatura de Administración y Finanzas Universidad Panamericana**")
st.write("Fechas: 2021 - 2023")
st.divider ()
st.write("**EDUCACIÓN**")
st.markdown("**- Licenciatura en Administración y Finanzas Universidad Panamericana, campus Guadalajara**")
st.write("Fechas: 2020 - a la fecha")
st.markdown("**- Especialidad en Finanzas Corporativas**")
st.write("Fechas: 2023")
st.divider ()
st.write("**IDIOMAS**")
st.markdown("- Inglés Avanzado")
st.markdown("- Francés Básico")
st.divider ()
st.write("**HABILIDADES**")
st.markdown("- Certificación de Microsoft Office")
st.markdown("- TOEFL 610 puntos")
